'use strict';
const DRAFT_KEY='panxrt-admin-dev-draft-v3';
let data=null,selectedWorkId=null,selectedBrandId=null,currentTab='works',toastTimer=null,frameReady=false,frameHeight=800;
const $=id=>document.getElementById(id),clone=v=>JSON.parse(JSON.stringify(v)),esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function mediaUrl(src){if(!src)return'';if(/^https?:\/\//i.test(src))return src;return src.startsWith('/')?'..'+src:'../'+src.replace(/^\.\//,'')}
function uuid(){return crypto.randomUUID?crypto.randomUUID():'id-'+Date.now()+'-'+Math.random().toString(16).slice(2)}
function toast(m){const n=$('toast');n.textContent=m;n.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>n.classList.remove('show'),1400)}
function saveQuiet(){localStorage.setItem(DRAFT_KEY,JSON.stringify(data))}
function work(){return data?.works.find(x=>x.id===selectedWorkId)||null}function brand(){return data?.brands.find(x=>x.id===selectedBrandId)||null}
async function load(){const r=await fetch('../content.json',{cache:'no-store'});if(!r.ok)throw new Error('Не удалось загрузить content.json');const server=await r.json(),draft=localStorage.getItem(DRAFT_KEY);if(draft){try{data=JSON.parse(draft);toast('Открыт локальный черновик')}catch{data=clone(server)}}else data=clone(server);data.works=Array.isArray(data.works)?data.works:[];data.brands=Array.isArray(data.brands)?data.brands:[];data.categories=Array.isArray(data.categories)?data.categories:[];selectedWorkId=data.works[0]?.id||null;renderAll()}
function sendFrame(type,extra={}){if(!frameReady)return;$('mosaicFrame').contentWindow.postMessage({source:'panxrt-admin',type,...extra},location.origin)}
function renderFrame(){sendFrame('render',{data:clone(data),selectedId:selectedWorkId});fitFrame()}
function fitFrame(){const viewport=$('frameViewport'),iframe=$('mosaicFrame'),scaler=$('frameScaler'),base=Number($('preview-size').value)||1200;iframe.style.width=base+'px';iframe.style.height=frameHeight+'px';const available=Math.max(200,viewport.clientWidth-16),scale=Math.min(1,available/base);iframe.style.transform='scale('+scale+')';scaler.style.width=(base*scale)+'px';scaler.style.height=(frameHeight*scale)+'px'}
function moveWork(sourceId,targetId){if(!sourceId||sourceId===targetId)return;const a=data.works.findIndex(x=>x.id===sourceId),b=data.works.findIndex(x=>x.id===targetId);if(a<0||b<0)return;const [item]=data.works.splice(a,1);data.works.splice(b,0,item);selectedWorkId=sourceId;saveQuiet();renderAll();toast('Плитка переставлена')}
addEventListener('message',e=>{if(e.origin!==location.origin||e.data?.source!=='panxrt-mosaic-frame')return;if(e.data.type==='ready'){frameReady=true;renderFrame()}if(e.data.type==='select'){selectedWorkId=e.data.id;selectedBrandId=null;renderInspector();sendFrame('select',{id:selectedWorkId})}if(e.data.type==='reorder')moveWork(e.data.sourceId,e.data.targetId);if(e.data.type==='height'){frameHeight=Math.max(500,Math.min(12000,Number(e.data.height)||800));fitFrame()}});
function renderAll(){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('is-active',b.dataset.tab===currentTab));$('worksWorkspace').hidden=currentTab!=='works';$('brandsWorkspace').hidden=currentTab!=='brands';$('floating-add').hidden=currentTab!=='works';renderFrame();renderBrands();renderInspector()}
function renderBrands(){const box=$('brandList');box.innerHTML='';data.brands.forEach(b=>{const n=document.createElement('div');n.className='brand-item'+(b.id===selectedBrandId?' is-active':'');n.innerHTML='<img src="'+esc(mediaUrl(b.src))+'" alt=""><strong>'+esc(b.name||'Без названия')+'</strong>';n.onclick=()=>{selectedBrandId=b.id;selectedWorkId=null;renderAll()};box.append(n)})}
function renderInspector(){const w=work(),b=brand();$('emptyInspector').hidden=!!(w||b);$('workEditor').hidden=!w;$('brandEditor').hidden=!b;if(w)renderWorkEditor(w);if(b)renderBrandEditor(b)}
function estimated(w){return{w:Math.round(Number(w.cardW)||Number(w.width)*200||400),h:Math.round(Number(w.cardH)||Number(w.height)*200||400)}}
function renderWorkEditor(w){$('editorTitle').textContent=w.title||'Без названия';$('titleInput').value=w.title||'';$('descriptionInput').value=w.description||'';$('srcInput').value=w.src||'';$('mediaTypeInput').value=w.mediaType==='video'?'video':'image';$('mediaFitInput').value=w.mediaFit==='contain'?'contain':'cover';$('fullProjectInput').checked=!!w.showFullProject;const s=estimated(w);$('cardWInput').value=Math.max(40,Math.min(1100,s.w));$('cardHInput').value=Math.max(40,Math.min(1100,s.h));labels();const box=$('categoryChecks');box.innerHTML='';data.categories.forEach(c=>{const l=document.createElement('label');l.innerHTML='<input type="checkbox" value="'+esc(c.id)+'" '+((w.categoryIds||[]).includes(c.id)?'checked':'')+'><span>'+esc(c.name)+'</span>';l.querySelector('input').onchange=()=>{w.categoryIds=[...box.querySelectorAll('input:checked')].map(x=>x.value);saveQuiet();renderFrame()};box.append(l)})}
function renderBrandEditor(b){$('brandEditorTitle').textContent=b.name||'Без названия';$('brandNameInput').value=b.name||'';$('brandSrcInput').value=b.src||'';$('brandPreviewImage').src=mediaUrl(b.src)}
function labels(){$('cardWValue').textContent=$('cardWInput').value+' px';$('cardHValue').textContent=$('cardHInput').value+' px'}
function updateWork(k,v,mirror=false){const w=work();if(!w)return;w[k]=v;if(mirror&&Object.prototype.hasOwnProperty.call(w,k+'Ru'))w[k+'Ru']=v;saveQuiet();renderFrame();$('editorTitle').textContent=w.title||'Без названия'}
function updateSize(){const w=work();if(!w)return;w.cardW=Number($('cardWInput').value);w.cardH=Number($('cardHInput').value);w.resizeMode='free';labels();saveQuiet();renderFrame()}
function resetSize(){const w=work();if(!w)return;delete w.cardW;delete w.cardH;delete w.resizeMode;saveQuiet();renderAll();toast('Размер сброшен')}
function addWork(){const w={id:uuid(),title:'New project',titleRu:'Новый проект',type:'Design',typeRu:'Дизайн',description:'',descriptionRu:'',body:'',bodyRu:'',src:'',mediaType:'image',projectMedia:[],width:1,height:1,showFullProject:false,categoryIds:[]};data.works.push(w);selectedWorkId=w.id;selectedBrandId=null;currentTab='works';saveQuiet();renderAll()}
function deleteWork(){const w=work();if(!w||!confirm('Удалить «'+(w.title||'Без названия')+'» из черновика?'))return;const i=data.works.findIndex(x=>x.id===w.id);data.works.splice(i,1);selectedWorkId=data.works[Math.min(i,data.works.length-1)]?.id||null;saveQuiet();renderAll()}
function addBrand(){const b={id:uuid(),name:'Новый бренд',src:''};data.brands.push(b);selectedBrandId=b.id;selectedWorkId=null;currentTab='brands';saveQuiet();renderAll()}
function deleteBrand(){const b=brand();if(!b||!confirm('Удалить бренд «'+(b.name||'Без названия')+'»?'))return;const i=data.brands.findIndex(x=>x.id===b.id);data.brands.splice(i,1);selectedBrandId=data.brands[Math.min(i,data.brands.length-1)]?.id||null;saveQuiet();renderAll()}
function exportJson(){const out=clone(data);out.revision=Math.max(1,Number(out.revision)||0)+1;const blob=new Blob([JSON.stringify(out,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='content-admin-preview.json';a.click();URL.revokeObjectURL(url)}
async function reset(){if(!confirm('Сбросить локальный черновик?'))return;localStorage.removeItem(DRAFT_KEY);data=null;selectedWorkId=null;selectedBrandId=null;await load()}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{currentTab=b.dataset.tab;if(currentTab==='works'){selectedBrandId=null;selectedWorkId=selectedWorkId||data.works[0]?.id||null}else{selectedWorkId=null;selectedBrandId=selectedBrandId||data.brands[0]?.id||null}renderAll()});
$('preview-size').onchange=()=>{fitFrame();renderFrame()};$('addWorkBtn').onclick=addWork;$('deleteWorkBtn').onclick=deleteWork;$('resetSizeBtn').onclick=resetSize;$('addBrandBtn').onclick=addBrand;$('deleteBrandBtn').onclick=deleteBrand;$('exportBtn').onclick=exportJson;$('resetBtn').onclick=reset;
$('titleInput').oninput=e=>updateWork('title',e.target.value,true);$('descriptionInput').oninput=e=>updateWork('description',e.target.value,true);$('srcInput').onchange=e=>updateWork('src',e.target.value);$('mediaTypeInput').onchange=e=>updateWork('mediaType',e.target.value);$('mediaFitInput').onchange=e=>updateWork('mediaFit',e.target.value);$('fullProjectInput').onchange=e=>updateWork('showFullProject',e.target.checked);$('cardWInput').oninput=updateSize;$('cardHInput').oninput=updateSize;$('brandNameInput').oninput=e=>{const b=brand();if(b){b.name=e.target.value;saveQuiet();renderBrands();$('brandEditorTitle').textContent=b.name}};$('brandSrcInput').onchange=e=>{const b=brand();if(b){b.src=e.target.value;saveQuiet();renderBrands();renderBrandEditor(b)}};
addEventListener('resize',fitFrame);load().catch(err=>{console.error(err);toast(err.message)});
